--- KATT Example: Spotify Metadata API ---

# Step 1

Search for Kaizers Orcherstra tracks, and get XML results

GET /search/1/track.json?q=kaizers+orchestra
Accept: application/json
< 200
< Content-Type: application/json
{
  "info": {
    "num_results": 445,
    "limit": 100,
    "offset": 0,
    "query": "kaizers orchestra",
    "type": "track",
    "page": 1,
    "{{_}}": "{{unexpected}}"
  },
  "tracks": []
}
