--- Converted from HAR https://ws.spotify.com/lookup/1/.json?uri=spotify:album:5AN6A9IR1g1xRgY0RoKOsT 2014-05-28T14:49:45.971Z ---

step 1
GET /lookup/1/.json?uri=spotify:album:5AN6A9IR1g1xRgY0RoKOsT
> Pragma: no-cache
> DNT: 1
> Accept-Encoding: gzip,deflate,sdch
> Host: ws.spotify.com
> Accept-Language: en-US,en;q=0.8,sv;q=0.6,ro;q=0.4,it;q=0.2
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
> Cache-Control: no-cache
> Cookie: spot=%7B%22t%22%3A1396114404%2C%22m%22%3A%22us%22%2C%22p%22%3Anull%2C%22u%22%3Anull%2C%22w%22%3Anull%7D; sp_userinfo=%7B%22username%22%3A%22andrei.neculau%22%2C%22displayName%22%3A%22andrei.neculau%22%2C%22email%22%3A%22andrei.neculau%40gmail.com%22%2C%22product%22%3A%22free%22%7D; plp=cd68cfa0ace62ecda7a1db90a515d7e30dd6976b; sp_fi=1; sp_cc=1; VISITORID=521617467
> Connection: keep-alive
< 200
< Date: Wed, 28 May 2014 14:49:46 GMT
< Content-Encoding: gzip
< Last-Modified: Tue, 27 May 2014 18:00:10 GMT
< Server: nginx
< Etag: 1401213610
< Vary: Accept-Charset
< Content-Type: application/json; charset=utf-8
< Access-Control-Allow-Origin: *
< Transfer-Encoding: chunked
< Connection: keep-alive
< Keep-Alive: timeout=10
< Expires: Thu, 29 May 2014 14:49:46 GMT
{"album": {"artist-id": "spotify:artist:1s1DnVoBDfp3jxjjew8cBR", "name": "Hjerteknuser", "artist": "Kaizers Orchestra", "external-ids": [{"type": "upc", "id": "886443444126"}], "released": "2010", "href": "spotify:album:5AN6A9IR1g1xRgY0RoKOsT", "availability": {"territories": "NO"}}, "info": {"type": "album"}}
